Repository r0gue-io/pop-node, pull requests merged in 2024-08, with the labels that each got.

#150 feat: burn and mint
  pallets/api/src/fungibles/mod.rs
  pallets/api/src/fungibles/tests.rs
  pop-api/integration-tests/contracts/fungibles/lib.rs
  pop-api/integration-tests/src/fungibles/mod.rs
  pop-api/integration-tests/src/fungibles/utils.rs
  pop-api/src/v0/assets/fungibles.rs
  runtime/devnet/src/config/api.rs
Labels: feature, api, pallet

#151 feat: asset management
  pallets/api/src/fungibles/mod.rs
  pallets/api/src/fungibles/tests.rs
  pop-api/examples/balance-transfer/lib.rs
  pop-api/examples/nfts/lib.rs
  pop-api/examples/place-spot-order/lib.rs
  pop-api/examples/read-runtime-state/lib.rs
  pop-api/integration-tests/contracts/.gitignore
  pop-api/integration-tests/contracts/create_token_in_constructor/Cargo.toml
  pop-api/integration-tests/contracts/create_token_in_constructor/lib.rs
  pop-api/integration-tests/contracts/fungibles/lib.rs
  pop-api/integration-tests/src/fungibles/mod.rs
  pop-api/integration-tests/src/fungibles/utils.rs
  pop-api/integration-tests/src/lib.rs
  pop-api/integration-tests/src/local_fungibles.rs
  pop-api/src/v0/assets/fungibles.rs
  runtime/devnet/src/config/api.rs
Labels: feature, api, pallet

#168 refactor: remove bare_call code duplication in integration test
  pop-api/integration-tests/src/fungibles/utils.rs
Labels: low priority, refactor

#163 refactor: generic extension crate to de-duplicate code between runtimes
  Cargo.lock
  Cargo.toml
  extension/Cargo.toml
  extension/src/lib.rs
  extension/src/tests.rs
  extension/src/v0.rs
  runtime/devnet/Cargo.toml
  runtime/devnet/src/config/api.rs
  runtime/devnet/src/config/contracts.rs
  runtime/devnet/src/extensions/mod.rs
  runtime/devnet/src/lib.rs
Labels: runtime, refactor

#153 feat: api events
  pallets/api/src/fungibles/mod.rs
  pallets/api/src/fungibles/tests.rs
  pallets/api/src/mock.rs
  pop-api/src/v0/assets/fungibles.rs
  runtime/devnet/src/config/api.rs
Labels: high priority

#179 chore: upgrade to 1.9.0
  Cargo.lock
  Cargo.toml
  runtime/devnet/src/config/contracts.rs
  runtime/devnet/src/lib.rs
  runtime/testnet/src/config/contracts.rs
  runtime/testnet/src/lib.rs
Labels: ready-for-review

#189 chore: upgrade to 1.11.0
  Cargo.lock
  Cargo.toml
  node/src/cli.rs
  node/src/command.rs
  node/src/service.rs
  runtime/devnet/Cargo.toml
  runtime/devnet/build.rs
  runtime/devnet/src/config/xcm.rs
  runtime/devnet/src/lib.rs
  runtime/testnet/Cargo.toml
  runtime/testnet/build.rs
  runtime/testnet/src/config/xcm.rs
  runtime/testnet/src/lib.rs
Labels: ready-for-review

#193 chore: upgrade to 1.12.0
  Cargo.lock
  Cargo.toml
  node/src/chain_spec.rs
  node/src/service.rs
  runtime/devnet/Cargo.toml
  runtime/devnet/build.rs
  runtime/devnet/src/config/xcm.rs
  runtime/devnet/src/lib.rs
  runtime/testnet/Cargo.toml
  runtime/testnet/build.rs
  runtime/testnet/src/config/xcm.rs
  runtime/testnet/src/lib.rs
Labels: ready-for-review

#194 chore: upgrade to 1.13.0
  Cargo.lock
  Cargo.toml
  node/src/chain_spec.rs
  runtime/devnet/Cargo.toml
  runtime/devnet/build.rs
  runtime/devnet/src/extensions.rs
  runtime/devnet/src/lib.rs
  runtime/testnet/build.rs
  runtime/testnet/src/extensions.rs
  runtime/testnet/src/lib.rs
Labels: ready-for-review

#201 fix: migrate integration tests from `paseo` to `polkadot` runtimes
  Cargo.lock
  Cargo.toml
  integration-tests/Cargo.toml
  integration-tests/src/chains/asset_hub_paseo/mod.rs
  integration-tests/src/chains/paseo/genesis.rs
  integration-tests/src/chains/paseo/mod.rs
  integration-tests/src/chains/pop_network/mod.rs
  integration-tests/src/lib.rs
  runtime/devnet/Cargo.toml
Labels: ready-for-review

#198 chore: upgrade v1.14.0
  Cargo.lock
  Cargo.toml
  integration-tests/Cargo.toml
  integration-tests/src/chains/asset_hub_paseo/mod.rs
  integration-tests/src/chains/paseo/genesis.rs
  integration-tests/src/chains/paseo/mod.rs
  integration-tests/src/chains/pop_network/mod.rs
  integration-tests/src/lib.rs
  node/Cargo.toml
  node/src/command.rs
  node/src/service.rs
  runtime/devnet/Cargo.toml
  runtime/devnet/src/config/xcm.rs
  runtime/devnet/src/lib.rs
  runtime/testnet/Cargo.toml
  runtime/testnet/src/config/xcm.rs
  runtime/testnet/src/lib.rs
Labels: ready-for-review

#178 chore: upgrade to 1.14.0
  Cargo.lock
  Cargo.toml
  integration-tests/Cargo.toml
  integration-tests/src/chains/asset_hub_paseo/mod.rs
  integration-tests/src/chains/paseo/genesis.rs
  integration-tests/src/chains/paseo/mod.rs
  integration-tests/src/chains/pop_network/mod.rs
  integration-tests/src/lib.rs
  node/Cargo.toml
  node/src/chain_spec.rs
  node/src/cli.rs
  node/src/command.rs
  node/src/service.rs
  runtime/devnet/Cargo.toml
  runtime/devnet/build.rs
  runtime/devnet/src/config/contracts.rs
  runtime/devnet/src/config/xcm.rs
  runtime/devnet/src/extensions.rs
  runtime/devnet/src/lib.rs
  runtime/testnet/Cargo.toml
  runtime/testnet/build.rs
  runtime/testnet/src/config/contracts.rs
  runtime/testnet/src/config/xcm.rs
  runtime/testnet/src/extensions.rs
  runtime/testnet/src/lib.rs
Labels: high priority, ready-for-review

#228 ci: add CI script for `pop-api` tests and integration tests
  .github/workflows/ci.yml
  Cargo.lock
  pop-api/Cargo.toml
  pop-api/integration-tests/Cargo.toml
  pop-api/integration-tests/build.rs
Labels: api, ready-for-review

#235 fix: mutable `self` required for dispatchable ink! methods
  pop-api/examples/fungibles/lib.rs
  pop-api/integration-tests/contracts/fungibles/lib.rs
Labels: documentation, question, api

#236 fix: api tests
  pallets/api/Cargo.toml
  pallets/api/src/fungibles/mod.rs
  pallets/api/src/fungibles/tests.rs
  pop-api/src/v0/assets/fungibles.rs
Labels: ready-for-review
