Repository r0gue-io/pop-node, pull requests merged in 2024-09, with the labels that each got.

#240 test: generic extension unit testing
  .github/workflows/ci.yml
  extension/src/decoding.rs
  extension/src/functions.rs
  extension/src/lib.rs
  extension/src/matching.rs
  extension/src/mock.rs
  extension/src/tests.rs
  integration-tests/src/lib.rs
  node/src/command.rs
  pallets/api/src/extension.rs
  pallets/api/src/fungibles/mod.rs
  pallets/api/src/lib.rs
  primitives/src/lib.rs
  runtime/devnet/src/config/api/mod.rs
  runtime/devnet/src/config/api/versioning.rs
  runtime/devnet/src/config/proxy.rs
  runtime/devnet/src/config/xcm.rs
  runtime/devnet/src/lib.rs
  runtime/testnet/src/config/proxy.rs
  runtime/testnet/src/config/xcm.rs
  runtime/testnet/src/extensions.rs
  runtime/testnet/src/lib.rs
Labels: ready-for-review

#273 test: primitives
  Cargo.lock
  primitives/Cargo.toml
  primitives/src/lib.rs
Labels: ready-for-final-review

#272 test: pallet api extension
  Cargo.lock
  extension/src/functions.rs
  extension/src/matching.rs
  extension/src/mock.rs
  pallets/api/src/extension.rs
  primitives/Cargo.toml
  primitives/src/lib.rs
  runtime/devnet/src/config/api/versioning.rs
Labels: ready-for-final-review

#271 refactor: encoding scheme
  Cargo.lock
  extension/src/functions.rs
  extension/src/matching.rs
  extension/src/mock.rs
  pallets/api/src/extension.rs
  pop-api/src/lib.rs
  pop-api/src/v0/mod.rs
  primitives/Cargo.toml
  primitives/src/lib.rs
  runtime/devnet/src/config/api/versioning.rs
Labels: ready-for-final-review

#280 refactor: api integration tests
  pop-api/examples/fungibles/lib.rs
  pop-api/integration-tests/contracts/create_token_in_constructor/Cargo.toml
  pop-api/integration-tests/contracts/fungibles/Cargo.toml
  pop-api/integration-tests/src/fungibles/mod.rs
  pop-api/integration-tests/src/fungibles/utils.rs
  pop-api/integration-tests/src/lib.rs
  pop-api/src/lib.rs
  pop-api/src/v0/fungibles.rs
  pop-api/src/v0/mod.rs
  runtime/devnet/src/config/assets.rs
Labels: ready-for-final-review

#284 feat(pallet-api/fungibles): benchmark read functions
  pallets/api/src/fungibles/benchmarking.rs
  pallets/api/src/fungibles/mod.rs
  pallets/api/src/fungibles/tests.rs
  pallets/api/src/fungibles/weights.rs
Labels: ready-for-final-review

#278 test: pallet api fungibles
  pallets/api/src/fungibles/mod.rs
  pallets/api/src/fungibles/tests.rs
  pallets/api/src/mock.rs
  runtime/devnet/src/config/api/versioning.rs
Labels: ready-for-final-review

#286 refactor: api event naming conventions
  pallets/api/src/fungibles/mod.rs
  pallets/api/src/fungibles/tests.rs
Labels: ready-for-final-review

#276 feat(CI): add ismp feature to CI, and choosing runtime for release
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: ready-for-final-review

#270 feat(devnet): add ismp
  .github/workflows/ci.yml
  .github/workflows/release.yml
  Cargo.lock
  Cargo.toml
  networks/devnet.toml
  node/Cargo.toml
  node/src/chain_spec.rs
  node/src/command.rs
  node/src/rpc.rs
  node/src/service.rs
  runtime/devnet/Cargo.toml
  runtime/devnet/src/config/ismp.rs
  runtime/devnet/src/config/mod.rs
  runtime/devnet/src/lib.rs
Labels: ready-for-final-review

#314 fix: separate test cases
  pop-api/examples/fungibles/tests.rs
Labels: blocked
