Repository r0gue-io/pop-node, pull requests merged in 2025-01, with the labels that each got.

#234 chore: upgrade to stable2407
  Cargo.lock
  Cargo.toml
  extension/Cargo.toml
  extension/src/mock.rs
  integration-tests/Cargo.toml
  integration-tests/src/chains/asset_hub/genesis.rs
  integration-tests/src/chains/asset_hub/mod.rs
  integration-tests/src/chains/pop_network/genesis.rs
  integration-tests/src/chains/relay/genesis.rs
  node/Cargo.toml
  node/src/command.rs
  node/src/rpc.rs
  node/src/service.rs
  pallets/api/Cargo.toml
  pallets/api/src/fungibles/tests.rs
  pop-api/Cargo.toml
  pop-api/integration-tests/Cargo.toml
  pop-api/integration-tests/contracts/create_token_in_constructor/Cargo.toml
  pop-api/integration-tests/contracts/fungibles/Cargo.toml
  pop-api/integration-tests/src/fungibles/mod.rs
  runtime/common/Cargo.toml
  runtime/common/src/lib.rs
  runtime/devnet/Cargo.toml
  runtime/devnet/src/config/api/mod.rs
  runtime/devnet/src/config/contracts.rs
  runtime/devnet/src/config/ismp.rs
  runtime/devnet/src/lib.rs
  runtime/mainnet/Cargo.toml
  runtime/mainnet/src/config/xcm.rs
  runtime/mainnet/src/lib.rs
  runtime/testnet/Cargo.toml
  runtime/testnet/src/config/api/mod.rs
  runtime/testnet/src/config/contracts.rs
  runtime/testnet/src/lib.rs
Labels: ready-for-final-review

#413 feat(nfts): `AccountBalance` deposit
  pallets/nfts/src/benchmarking.rs
  pallets/nfts/src/common_functions.rs
  pallets/nfts/src/features/approvals.rs
  pallets/nfts/src/features/atomic_swap.rs
  pallets/nfts/src/features/buy_sell.rs
  pallets/nfts/src/features/create_delete_item.rs
  pallets/nfts/src/features/transfer.rs
  pallets/nfts/src/impl_nonfungibles.rs
  pallets/nfts/src/lib.rs
  pallets/nfts/src/mock.rs
  pallets/nfts/src/tests.rs
  pallets/nfts/src/types.rs
  pallets/nfts/src/weights.rs
  runtime/devnet/src/config/assets.rs
  runtime/testnet/src/config/assets.rs
Labels: ready-for-final-review

#387 feat(nfts): add `CollectionApprovals` and `AccountBalance` storages, and general improvements
  pallets/nfts/README.md
  pallets/nfts/src/benchmarking.rs
  pallets/nfts/src/common_functions.rs
  pallets/nfts/src/features/approvals.rs
  pallets/nfts/src/features/atomic_swap.rs
  pallets/nfts/src/features/buy_sell.rs
  pallets/nfts/src/features/create_delete_collection.rs
  pallets/nfts/src/features/create_delete_item.rs
  pallets/nfts/src/features/transfer.rs
  pallets/nfts/src/impl_nonfungibles.rs
  pallets/nfts/src/lib.rs
  pallets/nfts/src/mock.rs
  pallets/nfts/src/tests.rs
  pallets/nfts/src/types.rs
  pallets/nfts/src/weights.rs
  runtime/devnet/src/config/assets.rs
  runtime/devnet/src/lib.rs
  runtime/testnet/src/config/assets.rs
Labels: pallet, ready-for-final-review

#388 feat(nonfungibles): add `pallet-api/nonfungibles`
  Cargo.lock
  pallets/api/Cargo.toml
  pallets/api/src/lib.rs
  pallets/api/src/mock.rs
  pallets/api/src/nonfungibles/benchmarking.rs
  pallets/api/src/nonfungibles/impls.rs
  pallets/api/src/nonfungibles/mod.rs
  pallets/api/src/nonfungibles/tests.rs
  pallets/api/src/nonfungibles/weights.rs
Labels: pallet

#425 chore: uplift to polkadot 2412
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  extension/src/functions.rs
  extension/src/lib.rs
  integration-tests/Cargo.toml
  integration-tests/src/chains/asset_hub/mod.rs
  integration-tests/src/chains/relay/genesis.rs
  node/Cargo.toml
  node/src/chain_spec.rs
  node/src/command.rs
  node/src/service.rs
  pallets/api/src/mock.rs
  pallets/nfts/src/benchmarking.rs
  pallets/nfts/src/common_functions.rs
  pallets/nfts/src/features/transfer.rs
  pallets/nfts/src/impl_nonfungibles.rs
  pallets/nfts/src/lib.rs
  primitives/src/lib.rs
  runtime/devnet/Cargo.toml
  runtime/devnet/src/config/api/versioning.rs
  runtime/devnet/src/lib.rs
  runtime/mainnet/Cargo.toml
  runtime/mainnet/src/lib.rs
  runtime/testnet/Cargo.toml
  runtime/testnet/src/config/api/versioning.rs
  runtime/testnet/src/lib.rs
Labels: ready-for-final-review

#444 refactor: reorder `Read` impl in fungibles pallet
  pallets/api/src/fungibles/mod.rs
  pallets/api/src/fungibles/tests.rs
  pallets/api/src/mock.rs
Labels: pallet, ready-for-final-review

#450 refactor: reuse `WeightInfo` in nonfungibles pallet test
  pallets/api/src/fungibles/tests.rs
Labels: ready-for-final-review

#449 chore: update collection details field to public
  pallets/nfts/src/types.rs
Labels: ready-for-final-review

#443 refactor(mainnet): add governance & pallet_sudo tests
  node/src/chain_spec.rs
  runtime/mainnet/src/config/governance.rs
  runtime/mainnet/src/config/mod.rs
  runtime/mainnet/src/lib.rs
Labels: ready-for-final-review

#438 refactor(mainnet): utility config
  runtime/mainnet/src/config/mod.rs
  runtime/mainnet/src/config/utility.rs
  runtime/mainnet/src/lib.rs
Labels: ready-for-final-review
